run:
	python3 main.py
	clean

clean:
	python3 main.py
	rm -rf __pycache__ && \
	rm -rf modules/__pycache__ && \
	rm -rf modules/geometry/__pycache__ && \
	rm -rf modules/utils/__pycache__
	rm -rf modules/materials/__pycache__
	rm -rf modules/oGL/__pycache__
	rm -rf modules/objects/__pycache__
